# Generated by Django 2.1.5 on 2019-02-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('publication_time', models.DateTimeField()),
                ('body', models.CharField(max_length=10000)),
                ('top_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
